<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>SPT_Korean_Localization</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>2.0.0</Version>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <FileVersion>2.0.0.0</FileVersion>
        <AssemblyName>SPT_Korean_Localization</AssemblyName>
        <OutputPath>$(ArtifactsRoot)build\$(Configuration)\ServerLocaleMod40\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
        <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SPTarkov.Common" Version="4.0.13" />
        <PackageReference Include="SPTarkov.DI" Version="4.0.13" />
        <PackageReference Include="SPTarkov.Server.Core" Version="4.0.13" />
    </ItemGroup>

</Project>
