<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.2.0</Version>
    <AssemblyName>GoLani.KoreanLocalization.Status</AssemblyName>
    <DefineConstants>$(DefineConstants);SPT_410</DefineConstants>
    <OutputPath>$(ArtifactsRoot)build\$(Configuration)\ServerLocaleStatus410\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\ServerLocaleStatus\*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="..\ClientLocalePrototype\ClientLocaleBuild.cs" Link="ClientLocaleBuild.cs" />
    <PackageReference Include="SPTarkov.Common" Version="4.1.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
  </ItemGroup>
</Project>
